version: '3.1'
services:
  db:
    image: mysql:5.7.39
    restart: always
    environment:
      - TZ=Europe/Moscow
      - MYSQL_INITDB_SKIP_TZINFO=True
      - MYSQL_DATABASE=bitrix
      - MYSQL_ROOT_PASSWORD=${MySQL_PASSWORD}
    labels:
      - traefik.enable=false
    volumes:
      - /opt/sites/dbs/${SITE_TEMPLATE}:/docker-entrypoint-initdb.d:ro
    networks:
      - backend
    command: mysqld --sql_mode='' --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb_strict_mode=OFF
  site:
    image: bitrix/php:221005
    restart: always
    privileged: true
    environment:
      - LANGUAGE=ru_RU
      - LANG=ru_RU.UTF-8
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=${MySQL_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
    volumes:
      - /opt/sites/files/${SITE_TEMPLATE}:/opt/site/base:ro
      - /opt/sites/configs/php.ini:/usr/local/etc/php/php.ini:ro
      - /opt/sites/configs/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint:ro
    ports:
      - 80
      - 2222
    networks:
      - frontend
      - backend
    extra_hosts:
      - "bitbucket.org.vvc:10.0.140.207"
    depends_on:
      - db
networks:
  frontend:
    external: true
  backend: {}
